networks:
  appnet:
    driver: bridge
    name: appnet

services:
  backend:
    image: ghcr.io/ripmarkus/kino-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - appnet

  nginx:
    image: ghcr.io/ripmarkus/kino-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - appnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro
      - ./ssl/selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro
