name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-maven-
      - name: Run tests
        run: ./mvnw test
      - name: Build Docker image
        run: docker build . --tag kinoxp:test
      - name: Test Docker container
        run: |
          docker run -d --name test-container -p 3000:8080 kinoxp:test
          sleep 30
          # Test if container is running and responding
          if docker ps | grep test-container; then
            echo "Container is running successfully"
          else
            echo "Container failed to start"
            exit 1
          fi
          docker stop test-container
          docker rm test-container
